services:
  db:
    image: mysql:8.1.0
    container_name: db
    restart: unless-stopped
    networks:
      - tt-network
    ports:
      - "3306:3306"
    env_file:
      - tasktracker-backend/app.env

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.4-rc
    networks:
      - tt-network
    ports:
      - '6379:6379'

  kafka:
    image: bitnami/kafka:3.3.2
    networks:
      - tt-network
    env_file:
      - tasktracker-backend/app.env

  app:
    build: ./tasktracker-backend
    networks:
      - tt-network
    ports:
      - "8080:8080"
    env_file:
      - tasktracker-backend/app.env
    depends_on:
      - db
      - redis
      - kafka

  front:
    build: ./tasktracker-front
    networks:
      - tt-network
    ports:
      - "8088:8088"

networks:
  tt-network:
    driver: bridge

volumes:
  db_data: