spring:
  datasource:
    url: jdbc:mysql://db:3306/tasktracker_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  flyway:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}